name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        type: string
        required: true
        description: The release version of this release. Must be a semantic version of the form X.Y.Z
      dry-run:
        type: boolean
        required: true
        description: Dry run, will not push branches.

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Input
        run: |
          echo "${{ github.event.inputs.releaseVersion }}" | perl -ne 'die unless m/^\d+\.\d+\.\d+$/'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Actor
        run: |
          # Release actor should be in the OWNER list
          cat OWNERS | grep ${{ github.actor }}
      - name: Release Prepare
        run: |
          git tag -a v${{ github.event.inputs.releaseVersion }} -m version ${{ github.event.inputs.releaseVersion }}
      - name: Release Perform
        if: ${{ github.event.inputs.dry-run != 'true' }}
        run: |
          git push https://${{ github.token }}@github.com/${{ github.repository }}.git v${{ github.event.inputs.releaseVersion }}
      - name: Publish Release
        if: ${{ github.event.inputs.dry-run != 'true' }}
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.event.inputs.releaseVersion }}